export enum TaxElementId {
  Employee = 'Employee',
  Employer = 'Employer',
  Base = 'Base',
  WithTax = 'WithTax',
  WithoutTax = 'WithoutTax',
  TaxAdditiveName = 'TaxAdditiveName',

  TotalGross = 'TotalGross',
  TotalGrossValue = 'TotalGrossValue',

  SocialContribution = 'SocialContribution',
  SocialContributionEmployer = 'SocialContributionEmployer',
  SocialContributionEmployee = 'SocialContributionEmployee',

  Retirement = 'Retirement',
  RetirementBase = 'RetirementBase',
  RetirementEmployer = 'RetirementEmployer',
  RetirementEmployee = 'RetirementEmployee',

  Disability = 'Disability',
  DisabilityBase = 'DisabilityBase',
  DisabilityEmployer = 'DisabilityEmployer',
  DisabilityEmployee = 'DisabilityEmployee',

  Sickness = 'Sickness',
  SicknessBase = 'SicknessBase',
  SicknessEmployer = 'SicknessEmployer',
  SicknessEmployee = 'SicknessEmployee',

  Accident = 'Accident',
  AccidentBase = 'AccidentBase',
  AccidentEmployer = 'AccidentEmployer',
  AccidentEmployee = 'AccidentEmployee',

  Fp = 'Fp',
  FpBase = 'FpBase',
  FpEmployer = 'FpEmployer',
  FpEmployee = 'FpEmployee',

  Fgsp = 'Fgsp',
  FgspBase = 'FgspBase',
  FgspEmployer = 'FgspEmployer',
  FgspEmployee = 'FgspEmployee',

  Fep = 'Fep',
  FepBase = 'FepBase',
  FepEmployer = 'FepEmployer',
  FepEmployee = 'FepEmployee',

  PpkBasicContribution = 'PpkBasicContribution',
  PpkBasicContributionBase = 'PpkBasicContributionBase',
  PpkBasicContributionEmployer = 'PpkBasicContributionEmployer',
  PpkBasicContributionEmployee = 'PpkBasicContributionEmployee',

  PpkAdditionalContribution = 'PpkAdditionalContribution',
  PpkAdditionalContributionBase = 'PpkAdditionalContributionBase',
  PpkAdditionalContributionEmployer = 'PpkAdditionalContributionEmployer',
  PpkAdditionalContributionEmployee = 'PpkAdditionalContributionEmployee',

  HealthInsuranceContributionBase = 'HealthInsuranceContributionBase',
  HealthInsuranceContributionBaseValue = 'HealthInsuranceContributionBaseValue',
  HealthInsuranceContribution = 'HealthInsuranceContribution',
  HealthInsuranceContributionValue = 'HealthInsuranceContributionValue',
  ZaniechPod = 'ZaniechPod',
  IncomeTax = 'IncomeTax',
  IncomeTaxValue = 'IncomeTaxValue',
  DeductibleExpenses = 'DeductibleExpenses',
  DeductibleExpensesValue = 'DeductibleExpensesValue',
  MiddleClassTaxRelief = 'MiddleClassTaxRelief',
  MiddleClassTaxReliefValue = 'MiddleClassTaxReliefValue',
  TaxRelief = 'TaxRelief',
  TaxReliefValue = 'TaxReliefValue',
  CumulativeTaxBase = 'CumulativeTaxBase',
  CumulativeTaxBaseValue = 'CumulativeTaxBaseValue',
  RetirementDisabilityCumulativeBase = 'RetirementDisabilityCumulativeBase',
  RetirementDisabilityCumulativeBaseValue = 'RetirementDisabilityCumulativeBaseValue',
  TaxPercentage = 'TaxPercentage',
  TaxPercentageValue = 'TaxPercentageValue',
  TotalNet = 'TotalNet',
  TotalNetValue = 'TotalNetValue',

  // Tax Additives

  PkupTaxAdditive = 'PkupTaxAdditive',
  PkupValueTaxAdditive = 'PkupValueTaxAdditive',
  PkupReduceTaxAdditive = 'PkupReduceTaxAdditive',
  PkupReduceValueTaxAdditive = 'PkupReduceValueTaxAdditive',

  BaseSalaryTaxAdditive = 'BaseSalaryTaxAdditive',
  SickPayTaxAdditive = 'SickPayTaxAdditive',
  SickAllowance1TaxAdditive = 'SickAllowance1TaxAdditive',
  SickAllowance2TaxAdditive = 'SickAllowance2TaxAdditive',
  SickAllowance3TaxAdditive = 'SickAllowance3TaxAdditive',
  SickAllowance4TaxAdditive = 'SickAllowance4TaxAdditive',
  SickAllowance5TaxAdditive = 'SickAllowance5TaxAdditive',
  MyBenefitTaxAdditive = 'MyBenefitTaxAdditive',
  RelocationBenefitTaxAdditive = 'RelocationBenefitTaxAdditive',
  LanguageCourseTaxAdditive = 'LanguageCourseTaxAdditive',
  BonusTaxAdditive = 'BonusTaxAdditive',
  QuoterBonusTaxAdditive = 'QuoterBonusTaxAdditive',
  AnnualBonusTaxAdditive = 'AnnualBonusTaxAdditive',
  SupplementalPayBonusTaxAdditive = 'SupplementalPayBonusTaxAdditive',
  ResearcherBonusTaxAdditive = 'ResearcherBonusTaxAdditive',
  OvertimeTaxAdditive = 'OvertimeTaxAdditive',
  Overtime50TaxAdditive = 'Overtime50TaxAdditive',
  Overtime100TaxAdditive = 'Overtime100TaxAdditive',
  OtherOvertimeTaxAdditive = 'OtherOvertimeTaxAdditive',
  OtherOvertime50TaxAdditive = 'OtherOvertime50TaxAdditive',
  OtherOvertime100TaxAdditive = 'OtherOvertime100TaxAdditive',
  Addon1TaxAdditive = 'Addon1TaxAdditive',
  Addon2TaxAdditive = 'Addon2TaxAdditive',
  Addon3TaxAdditive = 'Addon3TaxAdditive',
  VacationCompensationTaxAdditive = 'VacationCompensationTaxAdditive',
  PpkIncomeTaxAdditive = 'PpkIncomeTaxAdditive',
  BailiffDeductionTaxAdditive = 'BailiffDeductionTaxAdditive',
  MyBenefitDeductionTaxAdditive = 'MyBenefitDeductionTaxAdditive',
  CashAdvanceDeductionTaxAdditive = 'CashAdvanceDeductionTaxAdditive',
  EsppTaxAdditive = 'EsppTaxAdditive',
}
